version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  Install:
    - location: /scripts/install.sh
      timeout: 300
  AfterInstall:
    - location: /scripts/afterinstall.sh
      timeout: 300
  ApplicationStart:
    - location: /scripts/applicationstart.sh
