version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - #npm -f install
      - npm i
      - echo "Packages have been installed"
      - npm run build
      - echo "Storing Build Artifact to the Location"
      - /var/www/html
artifacts:
  paths:
    - '*'
